# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Allan Trevisan
tagline:          'Coding experiments and ideas'
description:      'Begin - to begin is half the work, let half still remain; again begin this, and thou wilt have finished.'
url:              http://atrevisan.tk
baseurl:          /

author:
  name:           'Allan Trevisan'
  url:            https://github.com/atrevisan

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/atrevisan/atrevisan.github.io
  
gems:
  - jekyll-sitemap
